name: Upload Python Package

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Update to the latest version of the checkout action

    - name: Set up Python
      uses: actions/setup-python@v2  # Update to the latest version of the setup-python action
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1  # Update to the latest version of the pypi publish action
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
